// const words = [
//     'abats', 'abbes', 'aboie', 'abois', 'aboli', 'abord', 'aboya',  'abris', 'abusa', 'abuse', 
//     'abêti', 'abîma', 'abîme', 'accot', 'accru', 'accus', 'acces', 'achat', 'acide', 'acier',
//     'acres', 'acter', 'actes', 'actif', 'adage',
//     'adieu', 'admet', 'admis', 'admit', 'adnes', 'adora', 'adore',
//     'affin', 'affut', 'agace', 'agate', 'agave', 'agaca', 'agent', 'agile', 'agira',
//     'agita', 'agite', 'agres', 
//     'ahuri', 'aidas', 'aider', 'aides', 'aidez', 'aidee', 'aient', 'aigle', 'aigre', 'aigri', 'aigus',
//     'aigue', 'ailes', 'ailee', 'aimai', 'aimas', 'aimer', 'aimes', 'aimez', 'aimat', 'aimee', 'aines',
//     'ainsi', 'airas', 'airer', 'aires', 'airez', 'airat', 'aises', 'aisee', 'aises', 'ajonc', 'ajour', 'ajout', 'album',
//     'aleph', 'algie', 'algol', 'algue', 'alias', 'alibi', 'alite', 'allai', 'allas', 'aller',
//     'allez', 'allat', 'allee', 'alors', 'alose', 'aloes', 'alpes', 'alpha', 'alpin', 'alter', 'altos',
//     'alune', 'aluni', 'alese', 'aleas', 'alesa', 'alene', 'amant', 'amati', 'ambla',
//     'amble', 'ambra', 'ambre', 'amena', 'amene', 'amers', 'amibe', 'amict', 'amies',
//     'amont', 'amour', 'amphi', 'ample', 'ampli', 'amure', 'amusa', 'amuse',
//     'amene', 'amere', 'anaux', 'anche', 'ancra', 'ancre', 'andin', 'aneth', 'anges', 'angle',
//     'anima', 'anime', 'anise', 'annee', 'anode', 'anses', 'antan',
//     'aorte', 'aphte', 'aplat', 'appas', 'appel', 'appui',
//     'apres', 'aptes', 'apura', 'apure', 'arabe', 'arasa', 'arase', 'arbre', 'arche', 'ardue', 'ardus',
//     'argon', 'argot', 'arias', 'aride', 'arien', 'armai', 'armas',
//     'armer', 'armes', 'armet', 'armez', 'armon', 'armat', 'armee', 'arque', 'arret',
//     'arums', 'arene', 'arête', 'arome', 'asile', 'assai', 'asses', 'assez',
//     'assis', 'assit', 'astre', 'athee', 'atlas', 'atoll', 'atome', 'atone', 'atour', 'atout', 'atèle', 'aubes',
//     'aucun', 'audio', 'audit', 'auges', 'auget', 'aurai', 'auras', 'aurez', 'aussi', 'autel', 'autos', 'autre', 'avais',
//     'avait', 'avala', 'avale', 'avant', 'avens', 'avenu', 'avers', 'aveux', 'avide', 'aviez',
//     'avion', 'avisa', 'avise', 'aviso', 'avoir', 'avons', 'avoua', 'avoue',
//     'avril', 'avere', 'avera', 'ayant',
//     'ayons', 'azure', 'aerer',
//     'ainee', 'aines', 'aieul', 'aieux', 'aioli', 'acres', 'agees', 'anier', 'anons', 'apres'
// ];

const words = [
    'abats', 'abbes', 'aboie', 'aboli', 'abord', 'abris', 'abuse', 
    'abeti', 'abime', 'accot', 'accru', 'accus', 'acces', 'achat', 'acide', 'acier',
    'acres', 'acter', 'actif', 'adage',
    'adieu', 'admet', 'adnes', 'adore',
    'affin', 'agace', 'agate', 'agave', 'agent', 'agile',
    'agite', 'agres', 
    'ahuri', 'aider', 'aigle', 'aigre',
    'aigue', 'ailes', 'aimer', 'aines',
    'ainsi', 'airer', 'aises', 'ajonc', 'ajour', 'ajout', 'album',
    'aleph', 'algie', 'algol', 'algue', 'alias', 'alibi', 'alite', 'aller',
    'alors', 'alose', 'aloes', 'alpes', 'alpha', 'alpin', 'alter', 'altos',
    'alune', 'aluni', 'alese', 'aleas', 'alesa', 'alene', 'amant', 'amati',
    'amble', 'ambre', 'amene', 'amers', 'amibe', 'amict', 'amies',
    'amont', 'amour', 'amphi', 'ample', 'ampli', 'amure', 'amuse',
    'amene', 'amere', 'anaux', 'anche', 'ancre', 'andin', 'aneth', 'anges', 'angle',
    'anime', 'anise', 'annee', 'anode', 'anses', 'antan',
    'aorte', 'aphte', 'aplat', 'appas', 'appel', 'appui',
    'apres', 'aptes', 'apure', 'arabe', 'arase', 'arbre', 'arche', 'ardue',
    'argon', 'argot', 'arias', 'aride', 'arien', 'armai',
    'armer', 'armes', 'armet', 'arque', 'arret',
    'arums', 'arene', 'arete', 'arome', 'asile', 'assai', 'assez',
    'assis', 'assit', 'astre', 'athee', 'atlas', 'atoll', 'atome', 'atone', 'atour', 'atout', 'atèle', 'aubes',
    'aucun', 'audio', 'audit', 'auges', 'auget', 'aurai', 'auras', 'aurez', 'aussi', 'autel', 'autos', 'autre', 'avais',
    'avait', 'avale', 'avant', 'avens', 'avenu', 'avers', 'aveux', 'avide',
    'avion', 'avisa', 'avise', 'aviso', 'avoir', 'avoue',
    'avril', 'avere', 'ayant',
    'ayons', 'azure', 'aerer',
    'ainee', 'aines', 'aieul', 'aieux', 'aioli', 'acres', 'agees', 'anier', 'anons', 'apres'
];

export default words;